const make=(tag,props={})=>Object.assign(document.createElement(tag),props);
const projectCards=[...document.querySelectorAll('.project')];
const filterBar=make('div',{className:'filter-bar'});
filterBar.setAttribute('role','group');filterBar.setAttribute('aria-label','تصفية المشاريع');
const categories=['bi','bi','ml','simulation'];
const projectCount=make('p',{className:'result-count'});projectCount.setAttribute('aria-live','polite');
[['all','الكل'],['bi','ذكاء الأعمال'],['ml','التعلم الآلي'],['simulation','المحاكاة']].forEach(([key,label])=>{
 const btn=make('button',{type:'button',textContent:label,className:'filter-button'});btn.setAttribute('aria-pressed',key==='all');
 btn.addEventListener('click',()=>{filterBar.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',b===btn));let n=0;projectCards.forEach((card,i)=>{card.hidden=key!=='all'&&categories[i]!==key;if(!card.hidden)n++});projectCount.textContent=`المشاريع المعروضة: ${n} من 4`;});filterBar.append(btn);
});
document.querySelector('.projects').before(filterBar,projectCount);projectCount.textContent='المشاريع المعروضة: 4 من 4';
const dialog=make('dialog',{className:'project-dialog'});dialog.setAttribute('aria-labelledby','project-dialog-title');
const close=make('button',{type:'button',className:'dialog-close',textContent:'إغلاق ×'});const content=make('div');dialog.append(close,content);document.body.append(dialog);
close.addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});
dialog.addEventListener('close',()=>document.body.classList.remove('modal-open'));
projectCards.forEach(card=>{const details=card.querySelector('details');const trigger=make('button',{type:'button',className:'project-open',textContent:'استكشف المشروع ↗'});trigger.setAttribute('aria-haspopup','dialog');trigger.setAttribute('aria-label','استكشف مشروع '+card.querySelector('h3').innerText.replaceAll('\n',' '));trigger.addEventListener('click',()=>{content.replaceChildren();const tag=card.querySelector('.tag').cloneNode(true);const title=make('h2',{id:'project-dialog-title',textContent:card.querySelector('h3').innerText.replaceAll('\n',' ')});const desc=card.querySelector('.project-body > p').cloneNode(true);const heading=make('h3',{textContent:'ما الذي يتضمنه المشروع؟'});const info=details.querySelector('p').cloneNode(true);content.append(tag,title,desc,heading,info);const extra=card.querySelector('.metrics,.chips');if(extra)content.append(extra.cloneNode(true));content.append(make('p',{className:'dialog-note',textContent:'مشروع أكاديمي / تدريب تعاوني'}));document.body.classList.add('modal-open');dialog.showModal()});details.replaceWith(trigger)});
const panels=[...document.querySelectorAll('.timeline')];const tabs=make('div',{className:'experience-tabs'});tabs.setAttribute('role','tablist');tabs.setAttribute('aria-label','الخبرة والتعليم');
function selectTab(index,focus=false){[...tabs.children].forEach((tab,i)=>{tab.setAttribute('aria-selected',i===index);tab.tabIndex=i===index?0:-1;panels[i].hidden=i!==index;if(focus&&i===index)tab.focus()})}
panels.forEach((panel,i)=>{const tab=make('button',{type:'button',id:`experience-tab-${i}`,textContent:i?'التعليم':'الخبرة العملية'});tab.setAttribute('role','tab');tab.setAttribute('aria-controls',`experience-panel-${i}`);panel.id=`experience-panel-${i}`;panel.setAttribute('role','tabpanel');panel.setAttribute('aria-labelledby',tab.id);panel.tabIndex=0;tab.addEventListener('click',()=>selectTab(i));tab.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();selectTab(e.key==='Home'?0:e.key==='End'?1:1-i,true)}});tabs.append(tab)});panels[0].before(tabs);selectTab(0);
const searchTools=make('div',{className:'certificate-tools'});const searchLabel=make('label',{textContent:'ابحث عن شهادة أو جهة'});const search=make('input',{type:'search',placeholder:'مثال: Python أو IBM',id:'certificate-search'});searchLabel.htmlFor=search.id;const yearLabel=make('label',{textContent:'السنة'});const year=make('select',{id:'certificate-year'});yearLabel.htmlFor=year.id;[['all','كل السنوات'],['2026','2026'],['2025','2025']].forEach(([value,text])=>year.append(make('option',{value,textContent:text})));const first=make('div');first.append(searchLabel,search);const second=make('div');second.append(yearLabel,year);searchTools.append(first,second);list.before(searchTools);const certStatus=make('p',{className:'result-count'});certStatus.setAttribute('role','status');list.after(certStatus);
function filterCertificates(){let n=0;const q=search.value.trim().toLowerCase();[...list.children].forEach(row=>{row.hidden=!(row.textContent.toLowerCase().includes(q)&&(year.value==='all'||row.querySelector('time').textContent===year.value));if(!row.hidden)n++});certStatus.textContent=n?`الشهادات والدورات المعروضة: ${n} من 11`:'لا توجد نتائج. جرّب كلمة أخرى أو اختر كل السنوات.'}
search.addEventListener('input',filterCertificates);year.addEventListener('change',filterCertificates);filterCertificates();
const copy=make('button',{type:'button',className:'copy-email',textContent:'نسخ البريد الإلكتروني'});const copyStatus=make('p',{className:'copy-status'});copyStatus.setAttribute('role','status');document.querySelector('.contact-links').after(copy,copyStatus);copy.addEventListener('click',async()=>{try{await navigator.clipboard.writeText('O.alnasser03@gmail.com');copyStatus.textContent='تم نسخ البريد الإلكتروني';}catch{copyStatus.textContent='تعذّر النسخ التلقائي. يمكنك تحديد البريد ونسخه يدويًا.'}});
const progress=make('div',{className:'reading-progress'});progress.setAttribute('aria-hidden','true');document.body.prepend(progress);let scheduled=false;function updateProgress(){const range=document.documentElement.scrollHeight-innerHeight;progress.style.transform=`scaleX(${range>0?scrollY/range:0})`;scheduled=false}addEventListener('scroll',()=>{if(!scheduled){scheduled=true;requestAnimationFrame(updateProgress)}},{passive:true});addEventListener('resize',updateProgress);updateProgress();
const navLinks=[...document.querySelectorAll('nav a')];const sectionObserver=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting)navLinks.forEach(a=>{if(a.hash==='#'+e.target.id)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current')})})},{rootMargin:'-15% 0px -60% 0px'});navLinks.forEach(a=>{const target=document.querySelector(a.hash);if(target)sectionObserver.observe(target)});
if(!matchMedia('(prefers-reduced-motion: reduce)').matches){const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('revealed');observer.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.section-head,.skill-grid article,.roadmap article').forEach(el=>{el.classList.add('reveal');observer.observe(el)})}
